# 开发环境配置
# ========================================

server:
  port: 8080

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_server?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: sakura_dev_root
    
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0

# 日志配置
logging:
  level:
    com.musicserver: debug
    org.springframework.security: debug
    org.mybatis: debug
    com.baomidou.mybatisplus: debug
    
# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 打印SQL语句到控制台（开发环境）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl